const employees = [
    {
        name: "Samantha Burnell",
        position: "CEO",
        specialty: "Strategic Leadership",
        age: 45,
        employeeID: "178943",
        email: "samantha.burnell@medicelite.biz",
        image: "images/samantha-burnell.jpg",
    },
    {
        name: "Leon Zhao",
        position: "Chief Technology Officer",
        specialty: "Cybernetic Enhancements",
        age: 39,
        employeeID: "112358",
        email: "leon.zhao@medicelite.biz",
        image: "images/leon-zhao.jpg",
    },
    {
        name: "Aria Torres",
        position: "HR Director",
        specialty: "Personnel Management",
        age: 37,
        employeeID: "337215",
        email: "aria.torres@medicelite.biz",
        image: "images/aria-torres.jpg",
    },
    {
        name: "Mikaela Rhys",
        position: "Logistics Coordinator",
        specialty: "Supply Chain Optimization",
        age: 29,
        employeeID: "654321",
        email: "mikaela.rhys@medicelite.biz",
        image: "images/mikaela-rhys.jpg",
    },
    {
        name: "Jaxon Creed",
        position: "Team Leader",
        specialty: "Tactical Response",
        age: 34,
        employeeID: "563780",
        email: "jaxon.creed@medicelite.biz",
        image: "images/jaxon-creed.jpg",
    },
    {
        name: "Tara Flint",
        position: "Field Medic",
        specialty: "Trauma Care",
        age: 32,
        employeeID: "287654",
        email: "tara.flint@medicelite.biz",
        image: "images/tara-flint.jpg",

    },
    {
        name: "Carlos Gomez",
        position: "Combat Medic",
        specialty: "Emergency Surgery",
        age: 36,
        employeeID: "298501",
        email: "carlos.gomez@medicelite.biz",
        image: "images/carlos-gomez.jpg",
    },
    {
        name: "Elise Hwang",
        position: "Communications Officer",
        specialty: "High-risk Zone Navigation",
        age: 28,
        employeeID: "234567",
        email: "elise.hwang@medicelite.biz",
        image: "images/elise-hwang.jpg",
    },
    {
        name: "Ivan Petrov",
        position: "Sniper/Overwatch",
        specialty: "Long-range Threat Neutralization",
        age: 40,
        employeeID: "545678",
        email: "ivan.petrov@medicelite.biz",
        image: "images/ivan-petrov.jpg",
    },
];

module.exports = employees;